### ISSUE TITLE
locale dependent $allComputersGroupName

### ISSUE THREAD

**Issue by gh-ix** [CharlesNRU/updates-automation#1]
Hello, please find attached a diff for a very simplicistic implementation of local dependent "All Computers" group name.
My powershell skills are far to waek to implement something more sophisticated, like checking WSUS or current locale.
So it's a simple config extension...
`--- /home/gharry-bsd/Downloads/tmp-share/Invoke-WSUSImportExportManager.ps1	2020-08-31 07:32:59.053029000 +0200
+++ /home/gharry-bsd/Downloads/tmp-share/Invoke-WSUSImportExportManager.new.ps1	2020-08-31 11:11:13.317294651 +0200
@@ -1344,7 +1344,7 @@
         [void]$WSUSXMLConfigRoot.AppendChild($WSUSXMLComputerGroups)
 
 
-        $allComputersGroup = $WSUSServer.GetComputerTargetGroups() | Where-Object {$_.name -eq "All Computers"}
+        $allComputersGroup = $WSUSServer.GetComputerTargetGroups() | Where-Object {$_.name -eq $allComputersGroupName}
         $allComputersGroupElement = $WSUSXMLConfig.CreateElement("ComputerGroup")
         $allComputersGroupElement.InnerText = $($allComputersGroup.Name)
 
@@ -1852,15 +1852,15 @@
             if($computerGroups){
 
                 [System.Xml.XmlElement]$allComputersGroupElement = $computerGroups.ComputerGroup
-                $allComputersGroupName = "All Computers"
+                # Defined via config file due to local dependency: $allComputersGroupName = "All Computers"
 
                 #Verify that the first computer group is "All Computers"
                 if($($allComputersGroupElement.'#text') -eq $allComputersGroupName){
                     $subGroups = $allComputersGroupElement.ComputerGroup
 
-                    $allComputersGroup = $WSUSServer.GetComputerTargetGroups() | Where-Object {$_.Name -eq "All Computers"}
+                    $allComputersGroup = $WSUSServer.GetComputerTargetGroups() | Where-Object {$_.Name -eq $allComputersGroupName}
 
-                    #$currentAllComputersSubGroups = $WSUSServer.GetComputerTargetGroups() | Where-Object {($_.Name -ne "All Computers") -and ($_.GetParentTargetGroup() -eq $allComputersGroup)} | Select-Object -ExpandProperty Name
+                    #$currentAllComputersSubGroups = $WSUSServer.GetComputerTargetGroups() | Where-Object {($_.Name -ne $allComputersGroupName) -and ($_.GetParentTargetGroup() -eq $allComputersGroup)} | Select-Object -ExpandProperty Name
                     foreach($subGroup in $subGroups){
                         if($subGroup -is [System.Xml.XmlElement]){#Computer group has sub groups
                             New-ComputerGroupFromXML -ParentComputerGroup $allComputersGroup -NewComputerGroupElement $subGroup
@@ -3036,6 +3036,21 @@
 }
 
 #endregion Parameter validation
+
+
+# Locale dependent "All Computers"
+If($Export -or $Import){
+
+    If($Import){
+        [string]$allComputersGroupName = $ImportOptions | Where-Object {$_.Name -eq "XMLConfiguration"} | Select-Object -ExpandProperty AllComputersGroupName -ErrorAction:Ignore
+        catch{ $allComputersGroupName = "All Computers" }
+    }elseif($Export){
+        [string]$allComputersGroupName = $ExportOptions | Where-Object {$_.Name -eq "XMLConfiguration"} | Select-Object -ExpandProperty AllComputersGroupName -ErrorAction:Ignore
+    }
+
+    IF([string]::IsNullOrEmpty($allComputersGroupName)) { $allComputersGroupName = "All Computers" }
+
+}
 
 #Try to load the UpdateServices module.
 Try {`

**Comment by gh-ix** [comment]
Argh, sorry, githubs' web interface skills are even lower :-( no idea how to attach or inster preformatted text.  Machines know everything better these days... no time to find out, sorry

**Comment by gharry-bsd** [comment]
Argh, sorry, githubs' web interface skills are even lower :-( no idea how to attach or inster preformatted text.  Machines know everything better these days... no time to find out, sorry

**Comment by gharry-bsd** [comment]
Argh, sorry, githubs' web interface skills are even lower :-( no idea how to attach or inster preformatted text.  Machines know everything better these days... no time to find out, sorry

**Comment by CharlesNRU** [comment]
Hello,

If I understand correctly, the issue is that the "All Computers" computer group is named differently if the OS locale is different. Is that right?

By the way, if you want to suggest a modification. You can do a pull request and it will automatically diff the difference between the original and your modified version.

**Comment by gh-ix** [comment]
Hello, thanks for lokking at it!
Yes, it's about the name of "All Computers", which is "Alle Computer" on my German WSUS e.g. Unfortunately, there's more issues - importing lead to 3000 unapproved updates :-( But 700 declined ones.  So I guess there's another problem with the approval ID assignement.
Never tried to find out how IDs are constructed… And not yet looked into SUSDB how it looks like after the failed imprort.  Like mentioned, I don't have much time doing Microsoft's job ;-) The lack of restoring approvals puzzeld my mind almost two decades ago and I used downstream replication from there on.  But now I replaced my only left top upstream WSUS (dropping anything but Server2008-20019 and the corresponding desktop variants – no Win10 1703 e.g, only 1607, 1809 because database size grew insanely). But the old WSUS had valuable XP/2003 decisions (especially for optional approvals) and I wanted to save/restore them - needing for one private game launcher only.  So replacing the WSUS has already consumed much more time than justifyable… Will see if sinking even more time can at least result in the first approval restire I've ever seen :-)

Thanks for the "pull request" hint – often heard but no I know what it means.  Will try one during asap.
-harry

**Comment by gh-ix** [comment]
Quick look into Function Import-WSUSConfigurationFromXML{} looks like "Remove" and "OptionalInstall" approvals are completely unhandled.
And declining anything which doesn't have an approval for sure doesn't reflect source state too.  I always had intentionally not-declined but unapproved updates.
If I'm not missing something big, this script results in the replication being at most "almost like" the source.
The story leading to this github site sounded to me like promising a solution for the "wsusutil export / import" desaster microsoft leaves. But the desaster isn't much different for my use case, even not if the – yet to be found – problem leading to no approval at all doesn't wouldn't occur.
With all respect to your work, you should make clear that this script does in no way replicate a offline WSUS instance.  It's not comparable to the online replication you get for regular downstream sync!
Thanks for publishing your efforts anyways!  But pelase make clear that it can't restore approvals identically!
Thanks,
-harry

**Comment by CharlesNRU** [comment]
Hello there, I just updated the script. The script will now save update approvals handling removal and optional approvals. I also fixed the "All Computers" and "Unassigned Computers" computer group having a different name if your locale is not english.
I did a couple of tests going from a French WSUS and English one without issues including the different types of approvals and deadline if applicable.
Hopefully you have some time to test it out.
Thank you again for the feedback.

**Comment by gh-ix** [comment]
Am 17.09.2020 um 02:24 schrieb Charles:
>
> Hello there, I just updated the script. The script will now save 
> update approvals handling removal and optional approvals. I also fixed 
> the "All Computers" and "Unassigned Computers" computer group having a 
> different name if your locale is not english.
> I did a couple of tests going from a French WSUS and English one 
> without issues including the different types of approvals and deadline 
> if applicable.
> Hopefully you have some time to test it out.
> Thank you again for the feedback.
>

Oh my lord, this is a great surprise.
Sounds fantastic.
Unfortunately, I don't have the oportunity to test in the near future.  
This is a shame; I'd love so much to have a real offline sync solution!
But I won't have something to test.  My decommisioned WSUS is histroy 
because I built the new from scratch (with going through XP/2003 and 2k8 
approvals).  But since it's in production and everything was fine, I 
deleted the old VM.
I do have backups, but it's unlikely that I'll find time to restore it 
for testing purposes.
But as soon as I have enough spare time, I'll start testing, or of 
course as soon as I need to move / replicate approvals anywhere else.

In case I can use it for professional service, I'll remember to do a 
significant donation.
I highly appreciate your work! Although I had urgently needed such a 
tool from year to year in the past, I never sat down and begun that 
tedious work (other than wrting down some notes).
Glad to know somebody who not only talks/knows, but was doing :-)
Thank you very much, please excuse my inability to return feedback!

-harry
